modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory

[[mods]] #mandatory
modId="torchslabmod" #mandatory
version="1.3" #mandatory
displayName="Torch Slab Mod" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/torchslabs-mod" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
authors="EndlesNights" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
A mod that allows the placement of torches & lanterns onto slab blocks. For Version 1.14.4
'''

[[dependencies.torchslabmod]]
    modId="forge"
    mandatory=true
    versionRange="[28.0.80,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.torchslabmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"